# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Book.create(title: "Lincoln in the Bardo",description: "Lincoln in the Bardo is a 2017 experimental novel by American writer George Saunders. It is Saunders's first full-length novel and was the New York Times hardcover fiction bestseller for the week of March 5, 2017. Saunders is better known for his short stories, reporting, and occasional essays",url: "https://en.wikipedia.org/wiki/Lincoln_in_the_Bardo#/media/File:Lincoln_in_the_Bardo_by_George_Saunders_first_edition.jpg")
Book.create(title: "Exit West", description: "Exit West is a novel published in 2017, written by Pakistani author Mohsin Hamid. This is Hamid's fourth novel. The main themes of the novel are emigration and refugee problems.",url: "https://images.gr-assets.com/books/1476668222l/32622470.jpg")
Book.create(title: "The Ministry of Utmost Happiness",description: "The Ministry of Utmost Happiness is the second novel by Indian writer Arundhati Roy, published in 2017, twenty years after her debut, The God of Small Things.",url: "https://images-na.ssl-images-amazon.com/images/I/51W0Yr9vsKL._SX338_BO1,204,203,200_.jpg")
Book.create(title: "The Hate U Give", description: "The Hate U Give is a young adult novel by Angie Thomas, that follows a protagonist drawn to activism after she witnesses the police shooting of her unarmed friend. Published February 28, 2017 by Balzer + Bray, The Hate U Give opened at number one on The New York Times young adult best-seller list. It is Thomas's debut novel.",url: "https://images-na.ssl-images-amazon.com/images/I/41tdlloETWL._SX258_BO1,204,203,200_.jpg")
Book.create(title: "Priestdaddy",description: "Priestdaddy is poet Patricia Lockwood's 2017 memoir.",url: "http://www.left-bank.com/sites/left-bank.com/files/Patricia%20Lockwood%20Event.jpg")
Book.create(title: "The Idiot",description: "The Idiot is an 2017 novel by Turkish American writer Elif Batuman. It is a bildungsroman, and concerns a college freshman, Selin, attending Harvard University.",url: "https://images.gr-assets.com/books/1485509262l/34025825.jpg")
Book.create(title: "Hunger",description: "Hunger: A Memoir of Body is a 2017 memoir by Roxane Gay.",url: "http://covers2.booksamillion.com/covers2/ebook/ImageType-100/0293-1/%7B444C74A0-3BC9-4C63-9307-5329E4B632D9%7DImg100.jpg")
Book.create(title: "Killers of the Flower Moon: The Osage Murders and the Birth of the FBI", description: "Killers of the Flower Moon: The Osage Murders and the Birth of the FBI is the third non-fiction book by American journalist David Grann. The book was released on April 18, 2017 by Doubleday.",url: "https://images-na.ssl-images-amazon.com/images/I/51Gk%2B%2ByHGHL._SY344_BO1,204,203,200_.jpg")
Book.create(title: "Pachinko",description: "Busan, Korea 1911: A club-footed, cleft-lipped man marries a fifteen-year-old beauty. The couple have one child, their beloved daughter Sunja.",url: "https://images.gr-assets.com/books/1462393298l/29983711.jpg")
Book.create(title: "Sour Heart: Stories",description: "I will never forget the first time I read Jenny Zhang ... I was stunned, moved and – quite frankly – a little jealous' Lena Dunham'Bold, startling brilliance' Miranda JulyThese seven startling stories of ...",url: "https://media.bloomsbury.com/rep/bj/9781408892411.jpg")
Book.create(title: "Anything Is Possible",description: "An unforgettable cast of small-town characters copes with love and loss from the No. 1 New York Times bestselling and Man Booker long-listed author of My Name is Lucy Barton Anything is Possible tells ...",url: "https://images-na.ssl-images-amazon.com/images/I/51mPEE0qUtL._SX336_BO1,204,203,200_.jpg")
Book.create(title: "What We Lose", description: "A short, intense and profoundly moving debut novel about race, identity, sex and death - from one of the National Book Foundation's 5 Under 35 Thandi is a black woman, but often mistaken for Hispanic or Asian. ...",url: "https://images.gr-assets.com/books/1492235781l/33280160.jpg")
Book.create(title: "Difficult Women",description: "Difficult Women is a 2017 short story collection by Roxane Gay.",url: "https://images.gr-assets.com/books/1478773519l/28818921.jpg")
Book.create(title: "Norse Mythology",description: "Bestselling and much loved author Neil Gaiman, whose novel American Gods has been adapted into a major television series, brings vividly to life the stories of Norse mythology that have inspired his ...",url: "http://www.neilgaiman.com/works/images/NorseMythology_Hardback_1473940163.jpg")
Book.create(title: "Her Body And Other Parties",description: "SHORTLISTED FOR THE NATIONAL BOOK AWARD FICTION PRIZE 2017'Brilliantly inventive and blazingly smart' Garth Greenwell'Impossible, imperfect, unforgettable' Roxane Gay'A wild thing ... covered in sequins ... ",url: "https://images.gr-assets.com/books/1485266434l/33375622.jpg")
MUser.create(m_username: "agutierrezt",m_password:"dasfdf1324324sdf")
MUser.create(m_username: "gcgarciab",m_password:"Cafmioewrl34")
MUser.create(m_username: "fdconejop",m_password:"fdsdfcvewr13r")
MUser.create(m_username: "ydgarciago",m_password:"yeisdsafx2314")
